# Generated by Django 5.1.15 on 2026-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='source_checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
