# Generated by Django 5.1.15 on 2026-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('snapshot_type', models.CharField(choices=[('revenue_daily', 'Revenue (daily)'), ('revenue_weekly', 'Revenue (weekly)'), ('revenue_monthly', 'Revenue (monthly)'), ('top_products', 'Top products'), ('customers', 'Customers')], max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['snapshot_type', 'period_start'],
                'indexes': [models.Index(fields=['snapshot_type', 'period_start'], name='analytics_a_snapsho_7392db_idx')],
                'unique_together': {('snapshot_type', 'period_start', 'period_end')},
            },
        ),
    ]
