# Generated by Django 5.1.15 on 2026-05-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('revenue_daily', 'Revenue (daily)'), ('revenue_weekly', 'Revenue (weekly)'), ('revenue_monthly', 'Revenue (monthly)'), ('top_products', 'Top products'), ('customers', 'Customers'), ('forecast', 'Forecast')], max_length=32),
        ),
    ]
